

# Monitoring and Security Block

- name: Dissable App armor docker entry to fix docker rasbian problems (trust)
  become: true
  shell: aa-remove-unknown && docker rm -f pihole
  ignore_errors: true


- name: Create Pihole container
  become_user: root
  become: true
  docker_container:
    name: "pihole"
    image: "pihole/pihole:latest"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    tls_hostname: "pihole.home"
    hostname: "pihole.home"
    ports: 
      - "{{ ansible_ssh_host }}:53:53/tcp"
      - "{{ ansible_ssh_host }}:53:53/udp"
      - "67:67/udp"
      - "8091:80"
    volumes:
      - '{{homedir}}/container-program-files/pihole/:/etc/pihole/'
      - '{{homedir}}/container-program-files/dnsmasq.d/:/etc/dnsmasq.d/'
      - '{{homedir}}/container-program-files/unbound.d/:/etc/unbound/'
    env: 
        TZ: "America/Toronto"
        cap_add: "NET_ADMIN"
        WEBPASSWORD: "{{ssh_pass}}"

- name: Create Glances SYS Monitor container
  docker_container:
    name: "glances-sys-monitor"
    image: "nicolargo/glances"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: 
      - "8093:61208"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    env: 
        GLANCES_OPT: "-w"

- name: Create DB mariadb
  docker_container:
    name: "mariadb"
    image: "ghcr.io/linuxserver/mariadb"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: 
      - "{{ ansible_ssh_host }}:9092:3306"
    volumes:
      - '{{homedir}}/container-program-files/mariadb/database:/var/lib/mysql'
    env: 
        TZ: "America/Toronto"
        MYSQL_ROOT_PASSWORD: "{{ssh_pass}}"
        MARIADB_USER: "{{ssh_user}}"
        MARIADB_PASSWORD: "{{ssh_pass}}"
        MARIADB_ROOT_PASSWORD: "{{ssh_pass}}"

- name: "Create myphpadmin container"
  ignore_errors: true
  shell: "sudo docker run --name myphpadmin -d --link mariadb:db -p 8095:80 phpmyadmin"

- name: Create Wordpress Container
  docker_container:
    name: "wordpress"
    image: "wordpress"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: 
      - "{{ ansible_ssh_host }}:9093:3306"
    volumes:
      - '{{homedir}}/container-program-files/wordpress:/var/www/html'
    env: 
        WORDPRESS_DB_HOST: mariadb
        WORDPRESS_DB_USER: "{{ssh_user}}"
        WORDPRESS_DB_PASSWORD: "{{ssh_pass}}"
        WORDPRESS_DB_NAME: wordpress_db
