# Docker Install (proper way)

- name: Install required system packages for Docker
  tags:
    - packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  tags:
    - packages
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  tags:
    - packages
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  tags:
    - packages
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  tags:
    - packages
  pip:
    name: docker