- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock-frontend"
  become: true
  tags: apt

- name: "update"
  shell: "apt-get update && \
          apt-get upgrade -y && \
          apt-get dist-upgrade -y && \
          apt-get autoremove -y && \
          apt-get autoclean -y"

- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 3600
